from typing import List, Optional

from lsp.client import LanguageClient

class LanguageClientManager:
    def __init__(self) -> None: ...
    def add_server(self, command: str, extensions: List[str]) -> None: ...
    def get_client(self, file_path: str) -> Optional[LanguageClient]: ...
    async def run_server(self, file_path: str) -> LanguageClient: ...
