from prompt_toolkit.buffer import Buffer
from sno_py.snoedit import SnoEdit


class DebugBuffer:
    def __init__(self, editor: SnoEdit, encoding: str = ...) -> None: ...
    @property
    def buffer_inst(self) -> Buffer: ...


class FileBuffer:
    def __init__(self, editor: SnoEdit, path: str, encoding: str = ...) -> None: ...
    @property
    def _is_new(self) -> bool: ...
    @property
    def buffer_inst(self) -> Buffer: ...
    def load(self) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def read_only(self) -> bool: ...
    def save(self) -> bool: ...
    @property
    def saved(self) -> bool: ...


class LogBuffer:
    def __init__(self, editor: SnoEdit, encoding: str = ...) -> None: ...
