# CC: https://github.com/nvimdev/nerdicons.nvim/
import json

min = 62721
max = 65535

python_str = '# Please do not edit this file, run scripts/generatory.py first\nicons = {\n'
indent = '    '

target = open('./src/sno_py/icons.py', 'w')
target.write(python_str)

with open('./scripts/glyphnames.json') as f:
    data = json.load(f)
    for i in data:
        if i != 'METADATA':
            code = int(str(data[i]['code']), 16)
            if code < min or code > max:
                char = str(data[i]['char'])
                target.write(indent + '"' + i + '": "' + char + '",\n')

target.write('}\n')
target.close()
